version: '2'
services:
  sc20-dev-machine:
    build: .
    image: ngohaibac/sc20-linux-dev
    container_name: sc20-linux-dev
    volumes:
      - "nfsmount:/opt"
      - ~/.ssh:/home/bacnh/.ssh:cached
    tty: true
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,acregmin=1,acdirmin=1
      device: ":/System/Volumes/Data/${PWD}"
